name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build
        run: |
          wasm-pack build --target web
          cp -r www/* pkg/
      - name: List contents of www directory
        run: |
          echo "Contents of www directory:"
          ls -la www
      - name: List contents of pkg directory
        run: |
          echo "Contents of pkg directory:"
          ls -la pkg
      - name: Debug info
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of current directory:"
          ls -la
      - name: Prepare for deployment
        run: |
          cd pkg
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Deploy to GitHub Pages"
          cd ..
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pkg
          force_orphan: true
